# Generated by Django 3.2.3 on 2021-05-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login'),
        ('questions', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_like',
            field=models.ManyToManyField(related_name='user_like_question', through='questions.QuestionLike', to='users.User'),
        ),
    ]
